### ISSUE TITLE
connect content matches between hreflangs

### ISSUE THREAD

**Issue by MarquiseRosier** [aemsites/stericycle-shared#354]
Setup helix-sitemap.yaml with an example of two pages in different languages, with entirely different paths; being co-located!

**Comment by rwcsrichardspencer** [comment]
Here's the FR-CA version of the "About Us" page: https://main--shredit--stericycle.aem.page/fr-ca/a-propos-de-shred-it

**Comment by kronnox** [comment]
Related to #300.

**Comment by kronnox** [comment]
@rwcsrichardspencer Since the pages on shredit won't share the same path suffix, we'll need to map them manually. This can be done in the page metadata (https://www.aem.live/developer/sitemap#specifying-the-primary-language-manually). You will have a default language (probably en-us) and map every copy of it in another language to the original:
![example](https://www.aem.live/developer/media_1aebb7da49a5deb3fb4824e7a625c23b856d41376.png?width=2000&format=webply&optimize=medium)
The `hreflang` tags in the header as well as the sitemap entries should get generated automatically.

**Comment by kronnox** [comment]
I'll validate that our sitemap configurations are set-up accordingly and modify the fr-ca homepage metadata so it can be used as an example

**Comment by kronnox** [comment]
Example page using the `primary-language-url` metadata field: https://main--shredit--stericycle.aem.page/fr-ca/a-propos-de-shred-it

Example sitemap configuration (tested and working):
```
sitemaps:
  shredit:
    origin: https://www.shredit.com
    lastmod: YYYY-MM-DD
    default: en-us
    languages:
      en-us:
        source: /en-us/query-index.json
        destination: /sitemap.xml
        hreflang: en-us
      fr-ca:
        source: /fr-ca/query-index.json
        destination: /sitemap.xml
        hreflang: fr-ca
```

Full documentation: https://www.aem.live/developer/sitemap#specifying-the-primary-language-manually
